package android.microntek.canbus.serializable;

import java.io.Serializable;

public class AirCondition implements Serializable {
    public int B_DIS_IMG = 0;
    public int DIS_IMG = 0;
    public int DIS_IMG1 = 0;
    public int acMax = -1;
    public boolean ariStateShow = true;
    public int b_acMax = -1;
    public boolean b_ariStateShow = true;
    public boolean b_leftShow = true;
    public boolean b_modeAc = false;
    public int b_modeAuto = 0;
    public int b_modeDual = -1;
    public boolean b_onOff = false;
    public int b_rearLock = -1;
    public boolean b_rightShow = true;
    public int b_seatHotLeft = -1;
    public int b_seatHotRight = -1;
    public boolean b_seatShow = true;
    public int b_tempLeft = -1;
    public int b_tempRight = -1;
    public boolean b_tempUnit = false;
    public boolean b_windDown = false;
    public boolean b_windFrontMax = false;
    public int b_windLevel = 0;
    public int b_windLevelMax = 0;
    public int b_windLoop = -1;
    public boolean b_windMid = false;
    public boolean b_windRear = false;
    public boolean b_windRearShow = true;
    public boolean b_windUp = false;
    public boolean b_wind_FrameShow = true;
    public int fast = -1;
    public int loopa = -1;
    public boolean modeAc = false;
    public int modeAuto = 0;
    public int modeDual = -1;
    public int normal = -1;
    public boolean onOff = false;
    public int rearLock = -1;
    public int seatHotLeft = -1;
    public int seatHotRight = -1;
    public boolean seatShow = true;
    public int soft = -1;
    public int tempLeft = -1;
    public int tempRight = -1;
    public boolean tempUnit = false;
    public boolean viewShow = true;
    public boolean windDown = false;
    public boolean windFrontMax = false;
    public int windLevel = 0;
    public int windLevelMax = 0;
    public int windLoop = -1;
    public boolean windMid = false;
    public boolean windRear = false;
    public boolean windRearShow = true;
    public boolean windUp = false;
    public boolean wind_FrameShow = true;
}
